training: 

  gamma: 0.90

  lr: 0.001

  train_batch_size: 15000

  model:
    fcnet_hiddens: [256, 256]
    fcnet_activation: swish
    vf_share_layers: false
    free_log_std: true

  optimizer: 
    type: adam

  use_critic: true

  use_gae: true

  lambda_: 0.95

  kl_coeff: 0.3

  sgd_minibatch_size: 7500

  num_sgd_iter: 2

  shuffle_sequences: true

  vf_loss_coeff: 0.5

  entropy_coeff: 0.01

  clip_param: 0.3

  vf_clip_param: 100

  kl_target: 0.01


environment:

  env: cassie-v0

  disable_env_checking: true
  clip_actions: true
framework:

  framework: torch
  enable_eager_tracing: true

rollouts: 

  num_rollout_workers: 20

  num_envs_per_worker: 1

  rollout_fragment_length: auto

  batch_mode: truncate_episodes

  recreate_failed_workers: true  

  observation_filter: MeanStdFilter  

  compress_observations: true  

evaluation: 

  evaluation_interval: 2

  evaluation_duration: 10

checkpointing: 

  export_native_model_files: true

debugging: 

  log_sys_usage: false


resources: 

  num_gpus: 1
  num_cpus: 20