gamma: 0.85

lr: 0.001

train_batch_size: 40000

model:
  fcnet_hiddens: [256, 256]
  fcnet_activation: swish
  vf_share_layers: false
  free_log_std: true 
  
optimizer: 
  type: adam

use_critic: true

use_gae: true

lambda_: 0.95

kl_coeff: 0.2

sgd_minibatch_size: 10000

num_sgd_iter: 4

shuffle_sequences: true

vf_loss_coeff: 0.5

entropy_coeff: 0.01

clip_param: 0.3

kl_target: 0.01

vf_clip_param: 1000.0

env: cassie-v0

disable_env_checking: true

clip_actions: true


framework: torch


num_rollout_workers: 20

num_envs_per_worker: 1

rollout_fragment_length: auto

batch_mode: truncate_episodes

recreate_failed_workers: true  

observation_filter: MeanStdFilter  

evaluation_interval: 2

evaluation_duration: 10

num_gpus: 0
num_cpus_per_worker: 1